services:
  sui-localnet:
    build:
      context: ./infra/sui
      dockerfile: Dockerfile.sui
    ports:
      - "9000:9000"
    volumes:
      - sui_data:/root/.sui
    healthcheck:
      test: ["CMD-SHELL", "curl -sf -X POST http://127.0.0.1:9000 -H 'content-type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"sui_getTotalTransactionBlocks\",\"params\":[]}' >/dev/null || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 60

  sui-cli:
    build:
      context: ./infra/sui
      dockerfile: Dockerfile.sui
    depends_on:
      sui-localnet:
        condition: service_healthy
    volumes:
      - move_cache:/root/.move
    tty: true
    stdin_open: true
    command: ["bash"]
volumes:
  sui_data:
  move_cache:
